### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by Meliiodas24** [Buntii/demoGrabber#1]
I tried this but it doesn't work please dm me on discord or something: nb'MeΙiodas#0001

**Comment by Buntii** [comment]
Your actual discord pls, that ain't your full tag. Some Information would be good too

**Comment by Meliiodas24** [comment]
nb'MeΙiodas#0001 sry

**Comment by Buntii** [comment]
still just #1, could you write it with spaces

**Comment by Buntii** [comment]
closed, no response
